/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guis;

import Account.Account;
import Account.Team;
import Account.TeamCollection;
import Channel.Channel;
import static Guis.CRUDTeamPanel.Accounts;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hachem
 */
public class SearchChannelsPanel extends javax.swing.JPanel {
    DefaultTableModel model;
    String[] colNames = {"Team Name", "Channel Name", "Channel Description", "Mention Allowed", "EveryBody Can Post", "Can Edit Own Messages"};
    /**
     * Creates new form SearchChannelsPanel
     */
    public SearchChannelsPanel() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(colNames);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchChanName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        searchBtn = new javax.swing.JButton();

        jLabel1.setText("Search Channels by Name:");

        jLabel2.setText("Channel Name:");

        searchChanName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchChanNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Search Results");

        resultsTable.setModel(model);
        jScrollPane1.setViewportView(resultsTable);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(searchChanName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(searchBtn))
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(searchChanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchChanNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchChanNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchChanNameActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        Account connectedAccount = Accounts.search("Helalami", "Password");
        ArrayList<Channel> foundChannels = connectedAccount.getTeams().getAllChannels().searchChannelsByKeyword(searchChanName.getText());
        if(!foundChannels.isEmpty()){
            Object [][] data = new Object[foundChannels.size()][colNames.length];
            for(int i = 0; i<foundChannels.size();i++){
                Channel ch = foundChannels.get(i);
                String teamName = "";
                for(Team t:connectedAccount.getTeams().getTeams()){
                    for(Channel c:t.getChannels().getChannels()){
                        if(c.equals(ch)){
                            teamName = t.getName();

                        }
                    }
                }
                data[i][0] = teamName;
                data[i][1] = ch.getChannel_name();
                data[i][2] = ch.getDescription();
                data[i][3] = ch.getSettings().isMention_allowed();
                data[i][4] = ch.getSettings().isEverybody_can_post();
                data[i][5] = ch.getSettings().isCan_edit_own_messages();
            }
            model.setDataVector(data, colNames);
        }
        else{
            model.setDataVector(null, colNames);
            JOptionPane.showMessageDialog(SearchChannelsPanel.this, "No Search Results", "Searching Students ...", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable resultsTable;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchChanName;
    // End of variables declaration//GEN-END:variables
}
